apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bbzbl

resources:
  - ./action-deployment.yaml

images:
  - name: hodelbbzbl/module-page-github-action
    newName: hodelbbzbl/module-page-github-action
    newTag: latest
